# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ef49396c0c80bee576f0476e2e1d364075a63e17aab750ff009c1b3d6f1fe2b07ed5e6ea736a33fd4f3160e343f9c387eabc1244c26af7be508fd97158778932

test:
  secret_key_base: 005ff5e2c64dfd6b677ab8042bfdffa5f8a307dae5d63ccf61c0258da66ec9de94305e9bed3686e7eead16d164db38cf8d68c4da5ca0dc7bb93a1151d1d56173

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
